version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      # These are your existing commands
      - mkdir -p deployment-package
      - pip install -r requirements.txt -t ./deployment-package
      - cp main.py ./deployment-package/
      - cd deployment-package
      - zip -r ../deployment_package.zip .
      - cd ..
  post_build:
    commands:
      # This is the NEW command to update the Lambda function
      - aws lambda update-function-code --function-name weather-app-backend --s3-bucket weather-app-lambda-code-aryaman-7z9x3y2a --s3-key deployment_package.zip

artifacts:
  files:
    # This section is no longer strictly needed but is good practice
    - deployment_package.zip